## -----------------------------------------------------------------------------
## *********** Flipped class problems for script 02
## -----------------------------------------------------------------------------


## -----------------------------------------------------------------------------
## **** Operations with vectors
## -----------------------------------------------------------------------------


## -----------------------------------------------------------------------------
## ** Given two equaly sized numerical vectors, implement
##    a general inner product (dot product, projection product)
##    of them in a function called
##    `inner_product` (use the stock function %*% only to **verify**
##    the correctness of your result).
##    Apply it to the example given below.
a <- c( 3, -4, 12)
b <- c(-3,  2,  5)


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Using the implemented `inner_product` function, create the function
##    `vect_norm` that implements the euclidean norm of a vector
##    Apply it to vector `a`


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Implement the Taxicab norm (or Manhattan norm, l^1 norm, l_1 distance)
##    in the function `taxicab_norm`. For details, see 
##    https://en.wikipedia.org/wiki/Norm_(mathematics)#Taxicab_norm_or_Manhattan_norm


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Implement the p-norm (l_p norm) in the function
##    `p_norm`. For details, see 
##    https://en.wikipedia.org/wiki/Norm_(mathematics)#p-norm

## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Implement the maximum norm in the function
##    `max_norm`. For details, see 
## https://en.wikipedia.org/wiki/Norm_(mathematics)#Maximum_norm_(special_case_of:_infinity_norm,_uniform_norm,_or_supremum_norm)


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Implement the Minkowski distance in the function
##    `minkowski_dist`. For details, see 
##    https://en.wikipedia.org/wiki/Minkowski_distance


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Given the vector
set.seed(1)
(x <- rgamma(20, shape = 3, rate = 2)) ## random variates from a gamma distr.
##    find the cumulative sum, the cumulative product, the cumulative minimum,
##    and cumulative maximum.


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Given the vector generated by
set.seed(1)
x <- rgamma(200, shape = 3, rate = 2) ## random variates from a gamma distr.
##    find its *approximate* (empirical) cumulative probability distribution
##    (Hint: use the function `cumtrapz` of the `pracma` package).
##    Plot the obtained function.
##    You can compare its plot to the one obtained using pgamma(),
##    that calculates the cumulative prob. distr. for any given quantile.


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## **** Subsetting
## -----------------------------------------------------------------------------


## Run the following code (the commented one only once) to access
## the father.son dataset.
## install.packages("UsingR")
library(UsingR)

## Pearson's data (heights of father and corresponding son)
## father.son is a data.frame. For now, ignore that fact (we are going to
## cover the details in a future lecture).
## We are going to extract two numerical vectors and work with that.
data(father.son)
dim(father.son)    ## Rows and columns
str(father.son)    ## Show structure
head(father.son)   ## First six pairs
tail(father.son)   ## Last six pairs

## Assigning to object names, and forgetting about the data.frame
fheight <- father.son$fheight
sheight <- father.son$sheight

## Vectors we are going to use
fheight
sheight


## -----------------------------------------------------------------------------
## ** Using positive indexes extract a *random sample* 20 values from the vector
##    `fheigh`.
##    Also extract a *simple random sample* of size 20
##    (Hint: use function `sample`).
##    Note: use `sample` to generate the indexes, not to extract the values
##          directly. This way, if later you would like to do, for example,
##          a regression, analysis on the subset, you could easily extract
##          the corresponding son's heights.


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Using logical indexes find those cases where the son's height differs from
##    the father's height by at least 3 inches (in excess or in defect).
##    Of this subset, find out how many cases had son taller and how many shorter
##    than father


## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Using logical indexes, verify the "Empirical rule", that states that when data
##    is drawn from a Normal distribution,

## * about 68% of the data is in the interval
##   `(mean(x) - sd(x), mean(x) + sd(x))`
## * about 95% of the data is in the interval
##   `(mean(x) - 2 * sd(x), mean(x) + 2 * sd(x))`
## * about 99.7% of the data is in the interval
##   `(mean(x) - 3 * sd(x), mean(x) + 3 * sd(x))`
## Hint: use "x <- rnorm(n)" to randomly generate a sample of size n from a standard
##       normal distribution. Use n = $1000$

## * Begin solution
## * End solution


## -----------------------------------------------------------------------------
## ** Using negative indexes, starting from the data below
data("BJsales")
help(BJsales)
##    that is a time series object (`ts) that we coerce to a numeric vector
sales <- as.numeric(BJsales)
##    using negative indexes find:
##    1) the first differences (explanation in link)
##       https://people.duke.edu/~rnau/411diff.htm#firstdiff
##       You can verify that the result should match the one of
##       the function `diff`
##    2) the one period simple return R_t
##    3) the continuously compounded return r_t
##    For 2) and 3) see page 10 of pdf added to flipped class module
##       (below this script)
##    Round 2) and 3) to 4 decimals.


## * Begin solution
## * End solution
